POST https://sprintlyserver.onrender.com/api/User
Content-Type: application/json

# {
#   "title": "Its very Weyward",
#   "description": "you already know Weyward.",
#   "projectName": "Sprintly",
#   "assignee": "Bob",
#   "status": "Pending",
#   "priority": "High",
#   "startDate": "2025-01-13T00:00:00.000+00:00",
#   "endDate": "2025-01-26T00:00:00.000+00:00",
#   "comments": [
#     { "username": "User1", "text": "Looks good." }
#   ]
# }

GET https://sprintlyserver-0k0g.onrender.com/requests/get_all_requests


